# Generated by Django 4.2.6 on 2023-10-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('address', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
                ('reference', models.CharField(blank=True, max_length=2500, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unsex', 'Unsex')], max_length=255)),
                ('description', models.TextField()),
                ('image_path', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Adopted', 'Adopted'), ('Pending', 'Pending')], max_length=255)),
                ('suburb', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(choices=[('NSW', 'NSW'), ('QLD', 'QLD'), ('VIC', 'VIC'), ('ACT', 'ACT'), ('TAS', 'TAS'), ('NT', 'NT'), ('SA', 'SA'), ('WA', 'WA')], max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Decline', 'Decline')], max_length=10)),
                ('application_note', models.TextField()),
                ('adoption_date', models.DateTimeField(null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescues_site.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescues_site.customuser')),
            ],
        ),
    ]
